version: '3.8'
services:
  messenger:
    build: ./messenger
    ports:
      - 8080:8080
    environment:
      - HOST=messenger
      - GPT_HOST=gpt
  gpt:
    build: ./gpt
    ports:
      - 8081:8081
    environment:
      - HOST=gpt
