name: Webapp Client Eslint and Prettier Workflow

on:
  push:
    paths: [ 'webapp-client/**' ]
    branches: [ main ]
  pull_request:
    paths: [ 'webapp-client/**' ]
    branches: [ main ]

  workflow_dispatch:

jobs:
  eslint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Installs npm modules
      - name: Install
        working-directory: ./webapp-client
        run: npm install

      # Runs eslint check
      - name: Eslint
        working-directory: ./webapp-client
        run: npm run lint
      
      # Runs prettier check
      - name: Prettier
        working-directory: ./webapp-client
        run: npm run prettier
